# Set this to "low" to reduce number of boot messages
verbosity: normal

# Try adjusting this if you have compatibility problems with other plguins.
# Default: "lowest". Can also use "low", "normal", "high", "highest".
priority: lowest

powerarmour:
#
# Block style is as follows:
#
# NAME_OF_ABILITY:
#   armourdamage: true or false
#   equipment:
#     head: (optional)
#     body: (optional)
#     legs: (optional)
#     feet: (optional)
#     hand: (optional)
#  protection:
#     - A
#     - LIST
#     - OF
#     - VALUES
#
# Available values for the protection list are:
#
#  DAMAGE_ALL
#  DAMAGE_FIRE
#  DAMAGE_LAVA
#  DAMAGE_ENTITY_ATTACK
#  DAMAGE_BLOCK_EXPLOSION 
#  DAMAGE_ENTITY_EXPLOSION 
#  DAMAGE_CONTACT 
#  DAMAGE_DROWNING 
#  DAMAGE_FALL 
#  DAMAGE_SUFFOCATION
#

  WATERPROOF:
    armourdamage: false
    equipment:
      head: LEATHER_HELMET
      body: LEATHER_CHESTPLATE
      legs: LEATHER_LEGGINGS
      feet: LEATHER_BOOTS
    protection:
      - DAMAGE_DROWNING
 
  FIREPROOF:
    armourdamage: false
    equipment:
      body: GOLD_CHESTPLATE
      legs: GOLD_LEGGINGS
      feet: GOLD_LEGGINGS
      hand: WATER_BUCKET
    protection:
      - DAMAGE_FIRE
      - DAMAGE_LAVA

  BOMBPROOF:
    armourdamage: true
    equipment:
      head: IRON_HELMET
      body: IRON_CHESTPLATE
      legs: IRON_LEGGINGS
      feet: IRON_BOOTS
    protection:
      - DAMAGE_ENTITY_EXPLOSION
      - DAMAGE_BLOCK_EXPLOSION

  FEATHERWEIGHT:
    armourdamage: false
    equipment:
      feet: LEATHER_BOOTS
      hand: FEATHER
    protection:
      - DAMAGE_FALL

  MONSTERPROOF:
    armourdamage: true
    equipment:
      head: GOLD_HELMET
    protection:
      - DAMAGE_ENTITY_ATTACK

  INVINCIBLE:
    armourdamage: true
    equipment:
      head: DIAMOND_HELMET
      body: DIAMOND_CHESTPLATE
      legs: DIAMOND_LEGGINGS
      feet: DIAMOND_BOOTS
      hand: DIAMOND_SWORD
    protection:
      - DAMAGE_ALL

